### PR TITLE
Add fix command

### LINKED ISSUE #21: The package doesn't support the "fix" command.
**Description**
Currently the package doesn't support the "fix" command, if you run ``` metrics fix <directory> ```it will throw an error with the following: ```Usage: metrics analyze [arguments] <directories>```.

image

**Why do you consider it necessary?**
It would be very valuable to have this functionality since there are many rules that can be corrected with this command and a lot of time that can be saved.

### PR DESCRIPTION
**Pull request by byshy**
Like the analyze command, I added a fix command that utilizes the replacement defined inside each rule to automatically replace the fixes

You can run the command on the example/lib and it will identify the 3 issues it has in the `main.dart` file, and fix only 1 (which has the replacement defined)
> dart run dart_code_linter:metrics fix example/lib

### CODE REVIEW

File: lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_first_or_null/prefer_first_or_null_rule.dart [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+import '../../../models/replacement.dart';
+import '../../../models/severity.dart';
+import '../../models/dart_rule.dart';
+import '../../rule_utils.dart';
+
+part 'visitor.dart';
+
+class PreferFirstOrNullRule extends DartRule {
+  static const ruleId = 'prefer-first-or-null';
+  static const warningMessage = 'Use first instead of accessing the element at zero index or using first.';
```
Comment (santitigaga) [inline lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_first_or_null/prefer_first_or_null_rule.dart:21]: please pull the changes from trunk to merge this PR

**Review by santitigaga — CHANGES_REQUESTED** [review]

**Comment by santitigaga** [comment]
@byshy  please pull changes

**Comment by byshy** [comment]
Done

**Comment by byshy** [comment]
As a quick note, before publishing the changes to pub get, we should run the dart formatter on the changed files (in this PR and the 3 before) since I have custom rules on my IDE to set the length of the dart line to 130, it should be 80, so we should run that then publish

File: lib/src/cli/models/parsed_arguments.dart [hunk 2]
```diff
@@ -30,4 +30,11 @@ class ParsedArguments {
               metric.id: argResults[metric.id] as Object,
         },
       );
+
+  factory ParsedArguments.fromArgsNoMetrics(ArgResults argResults) => ParsedArguments(
+        excludePath: argResults[FlagNames.exclude] as String,
+        rootFolder: argResults[FlagNames.rootFolder] as String,
```
Comment (santitigaga) [inline lib/src/cli/models/parsed_arguments.dart:36]: What do you think about keeping the jsonReportPath property?

File: lib/src/cli/commands/fix_lints_command.dart
Comment (santitigaga) [inline lib/src/cli/commands/fix_lints_command.dart:1]: Is it easy for you to add tests?

Comment (santitigaga) [inline lib/src/cli/commands/fix_lints_command.dart:1]: We need to document this too

File: lib/src/analyzers/lint_analyzer/lint_analyzer.dart [hunk 3]
```diff
@@ -141,6 +141,105 @@ class LintAnalyzer {
...
+      final updateMessage = contextsLength == 1
+          ? 'Fixing $filesLength file(s)'
+          : 'Fixing ${collection.contexts.indexOf(context) + 1}/$contextsLength contexts with $filesLength file(s)';
+      _logger?.progress.update(updateMessage);
+
+      for (final filePath in analyzedFiles) {
+        _logger?.infoVerbose('Fixing $filePath\n');
+
+        final unit = await context.currentSession.getResolvedUnit(filePath);
+        if (unit is ResolvedUnitResult) {
```
Comment (santitigaga) [inline lib/src/analyzers/lint_analyzer/lint_analyzer.dart]: I think this is exactly the same as `runCliAnalysiso` only the message changes. What do you think about extracting this logic to a new function that receives the `message` _Fixing_ and  _Analyzing_ so as not to duplicate code?

**Review by santitigaga — CHANGES_REQUESTED** [review]

File: lib/src/cli/models/parsed_arguments.dart (hunk 2 above)
Comment (byshy) [reply lib/src/cli/models/parsed_arguments.dart:36]: I removed it since the fix command already utilizes what the analyze do, so I thought no need for the report, we can keep it tho, I will add it

File: lib/src/cli/commands/fix_lints_command.dart
Comment (byshy) [reply lib/src/cli/commands/fix_lints_command.dart:1]: Sure thing 🫡

Comment (byshy) [reply lib/src/cli/commands/fix_lints_command.dart:1]: Will create a new PR for documenting all changes I made

**Comment by byshy** [comment]
Notes handled, I'm available for new notes if any 🙏

**Review by santitigaga — APPROVED** [review]

**Comment by byshy** [comment]
Amazing!!
Can we connect on linkedIn @santitigaga ?

**Comment by santitigaga** [comment]
@byshy  yes of course, https://linkedin.com/in/santiago-garcia-gil-742b38252/

**Comment by byshy** [comment]
Invitation sent
